'use client'

import { Card } from '@/components/ui/card'
import { ShieldAlert, AlertTriangle, Clock, FileCheck2, CheckCircle2 } from 'lucide-react'
import { api, RiskCase, RuleConfig } from '@/lib/api'
import { useFetchData } from '@/hooks/use-fetch-data'
import { ErrorCard } from '@/components/ui/error-card'

export function RiskCasesMetrics() {
  const { data, loading, error, refetch } = useFetchData<{ cases: RiskCase[]; rules: RuleConfig[] }>(
    async () => {
      const [cases, rules] = await Promise.all([api.getCases(), api.getRules()])
      return { cases, rules }
    },
  )

  const { cases = [] } = data ?? {}

  if (error) {
    return (
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        <ErrorCard
          title="Failed to Load Case Summary"
          message={error}
          onRetry={refetch}
          className="col-span-full"
        />
      </div>
    )
  }

  if (loading) {
    return (
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
        {[1, 2, 3, 4, 5].map((i) => (
          <Card key={i} className="p-5.5 space-y-3 bg-card border-0 rounded-2xl shadow-[0_4px_20px_-2px_rgba(0,0,0,0.04)]">
            <div className="h-3.5 bg-muted/40 rounded-lg w-1/2 animate-pulse" />
            <div className="h-7 bg-muted/20 rounded-lg w-1/3 animate-pulse" />
            <div className="h-3 bg-muted/20 rounded-lg w-2/3 animate-pulse" />
          </Card>
        ))}
      </div>
    )
  }

  const totalCases = cases.length
  const highPriority = cases.filter((c) => c.priority?.toLowerCase() === 'high').length
  const inProgress = cases.filter((c) =>
    ['Under Investigation', 'Corrective Action', 'Assigned', 'In Progress'].includes(c.status)
  ).length
  const pendingClosure = cases.filter((c) =>
    ['Pending Verification', 'Pending Closure'].includes(c.status)
  ).length
  const closedCount = cases.filter((c) => c.status === 'Closed').length

  const cards = [
    {
      label: 'Total Cases',
      value: `${totalCases}`,
      subtext: 'Total exception cases generated by rule evaluation engine',
      badge: 'Active Queue',
      badgeClass: 'bg-primary/10 text-primary border-primary/20',
      icon: <ShieldAlert className="w-4 h-4" />,
      iconColor: 'text-primary bg-primary/10 border-primary/20',
    },
    {
      label: 'High Priority',
      value: `${highPriority}`,
      subtext: highPriority > 0
        ? `${highPriority} critical case(s) requiring immediate inquiry`
        : 'Zero critical priority cases pending investigation',
      badge: highPriority > 0 ? 'Needs Review' : 'All Clear',
      badgeClass: highPriority > 0
        ? 'bg-destructive/10 text-destructive border-destructive/20'
        : 'bg-success/10 text-success border-success/20',
      icon: <AlertTriangle className="w-4 h-4" />,
      iconColor: highPriority > 0
        ? 'text-destructive bg-destructive/10 border-destructive/20'
        : 'text-success bg-success/10 border-success/20',
    },
    {
      label: 'In Progress',
      value: `${inProgress}`,
      subtext: 'Cases assigned and under active root-cause inquiry',
      badge: 'Active Inquiry',
      badgeClass: 'bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20',
      icon: <Clock className="w-4 h-4" />,
      iconColor: 'text-blue-600 dark:text-blue-400 bg-blue-500/10 border-blue-500/20',
    },
    {
      label: 'Pending Closure',
      value: `${pendingClosure}`,
      subtext: 'Cases submitted for 8-field system-validated closure',
      badge: 'Review Gate',
      badgeClass: 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20',
      icon: <FileCheck2 className="w-4 h-4" />,
      iconColor: 'text-amber-600 dark:text-amber-400 bg-amber-500/10 border-amber-500/20',
    },
    {
      label: 'Validated Closures',
      value: `${closedCount}`,
      subtext: 'Formal 8-field closures attested with verified evidence',
      badge: 'System Validated',
      badgeClass: 'bg-success/10 text-success border-success/20',
      icon: <CheckCircle2 className="w-4 h-4" />,
      iconColor: 'text-success bg-success/10 border-success/20',
    },
  ]

  return (
    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
      {cards.map((card) => (
        <Card
          key={card.label}
          className="p-5.5 bg-card border-0 rounded-2xl shadow-[0_4px_24px_rgba(0,0,0,0.04),0_1px_3px_rgba(0,0,0,0.02)] hover:shadow-[0_12px_32px_-4px_rgba(0,0,0,0.08)] dark:shadow-[0_10px_35px_rgba(0,0,0,0.35)] dark:bg-[#16181f] transition-all duration-200 group flex flex-col justify-between"
        >
          {/* Header row */}
          <div>
            <div className="flex items-center justify-between gap-2">
              <p className="text-[11px] uppercase font-mono tracking-wider font-semibold text-muted-foreground truncate">
                {card.label}
              </p>
              <div className={`w-8 h-8 rounded-lg border flex items-center justify-center shrink-0 transition-transform group-hover:scale-105 ${card.iconColor}`}>
                {card.icon}
              </div>
            </div>

            {/* Metric value and badge */}
            <div className="mt-2 flex items-baseline gap-2.5">
              <span className="text-2xl sm:text-3xl font-bold text-foreground font-mono tracking-tight">
                {card.value}
              </span>
              <span className={`text-[10px] font-mono font-medium px-1.5 py-0.5 rounded border shrink-0 ${card.badgeClass}`}>
                {card.badge}
              </span>
            </div>
          </div>

          {/* Explanatory footer */}
          <div className="mt-3 pt-2.5 border-t border-border/50">
            <p className="text-[11px] text-muted-foreground leading-relaxed">
              {card.subtext}
            </p>
          </div>
        </Card>
      ))}
    </div>
  )
}
