"""add_reconstruction_snapshots_table

Revision ID: 2ba199544f29
Revises:
Create Date: 2026-09-15 07:26:58.114174

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ba199544f29"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reconstruction_snapshots",
        sa.Column("snapshot_id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.String(length=50), nullable=False),
        sa.Column("case_id", sa.String(length=50), nullable=True),
        sa.Column("event_timestamp", sa.DateTime(), nullable=False),
        sa.Column("outcome", sa.String(length=20), nullable=False),
        sa.Column("explanation", sa.String(length=2000), nullable=False),
        sa.Column("reconstruction_payload", sa.JSON(), nullable=False),
        sa.Column("applicable_rule_version", sa.Integer(), nullable=True),
        sa.Column("applicable_rule_code", sa.String(length=50), nullable=True),
        sa.Column("evidence_completeness", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("snapshot_id"),
    )
    op.create_index(
        op.f("ix_reconstruction_snapshots_case_id"),
        "reconstruction_snapshots",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconstruction_snapshots_event_timestamp"),
        "reconstruction_snapshots",
        ["event_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reconstruction_snapshots_transaction_id"),
        "reconstruction_snapshots",
        ["transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reconstruction_snapshots_transaction_id"), table_name="reconstruction_snapshots"
    )
    op.drop_index(
        op.f("ix_reconstruction_snapshots_event_timestamp"), table_name="reconstruction_snapshots"
    )
    op.drop_index(
        op.f("ix_reconstruction_snapshots_case_id"), table_name="reconstruction_snapshots"
    )
    op.drop_table("reconstruction_snapshots")
    # ### end Alembic commands ###
