"""add_event_timestamp_to_transactions

Revision ID: cbbdff801f48
Revises: e8249540de23
Create Date: 2026-09-30 09:32:09.028287

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbbdff801f48"
down_revision: Union[str, Sequence[str], None] = "e8249540de23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions", sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(
        op.f("ix_transactions_event_timestamp"),
        "transactions",
        ["event_timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_event_timestamp"), table_name="transactions")
    op.drop_column("transactions", "event_timestamp")
    # ### end Alembic commands ###
