"""add_event_timestamp_to_transactions

Revision ID: cbbdff801f48
Revises: e8249540de23
Create Date: 2026-09-30 09:32:09.028287

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbbdff801f48"
down_revision: Union[str, Sequence[str], None] = "e8249540de23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    inspector = sa.inspect(op.get_bind())
    if "event_timestamp" not in {c["name"] for c in inspector.get_columns("transactions")}:
        op.add_column(
            "transactions", sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=True)
        )
    if "ix_transactions_event_timestamp" not in {
        ix["name"] for ix in inspector.get_indexes("transactions")
    }:
        op.create_index(
            op.f("ix_transactions_event_timestamp"),
            "transactions",
            ["event_timestamp"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_event_timestamp"), table_name="transactions")
    op.drop_column("transactions", "event_timestamp")
    # ### end Alembic commands ###
