"""add_remediation_replay_tables

Revision ID: e8249540de23
Revises: 2ba199544f29
Create Date: 2026-09-15 07:56:42.823411

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8249540de23"
down_revision: Union[str, Sequence[str], None] = "2ba199544f29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposed_controls",
        sa.Column("control_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
        sa.Column("amount_threshold", sa.Float(), nullable=False),
        sa.Column("bank_change_window_days", sa.Integer(), nullable=False),
        sa.Column(
            "required_approval_level", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("action_policy", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("control_id"),
    )
    op.create_index(
        op.f("ix_proposed_controls_is_active"), "proposed_controls", ["is_active"], unique=False
    )
    op.create_table(
        "remediation_replay_results",
        sa.Column("replay_id", sa.Integer(), nullable=False),
        sa.Column("control_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("transaction_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("case_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("event_timestamp", sa.DateTime(), nullable=False),
        sa.Column(
            "replay_determination", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("original_outcome", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column(
            "proposed_control_outcome", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("explanation", sqlmodel.sql.sqltypes.AutoString(length=3000), nullable=False),
        sa.Column("driving_facts", sa.JSON(), nullable=False),
        sa.Column("replay_payload", sa.JSON(), nullable=False),
        sa.Column("reconstruction_snapshot_id", sa.Integer(), nullable=True),
        sa.Column("executed_by", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("replay_id"),
    )
    op.create_index(
        op.f("ix_remediation_replay_results_case_id"),
        "remediation_replay_results",
        ["case_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_remediation_replay_results_control_id"),
        "remediation_replay_results",
        ["control_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_remediation_replay_results_event_timestamp"),
        "remediation_replay_results",
        ["event_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_remediation_replay_results_replay_determination"),
        "remediation_replay_results",
        ["replay_determination"],
        unique=False,
    )
    op.create_index(
        op.f("ix_remediation_replay_results_transaction_id"),
        "remediation_replay_results",
        ["transaction_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_remediation_replay_results_transaction_id"),
        table_name="remediation_replay_results",
    )
    op.drop_index(
        op.f("ix_remediation_replay_results_replay_determination"),
        table_name="remediation_replay_results",
    )
    op.drop_index(
        op.f("ix_remediation_replay_results_event_timestamp"),
        table_name="remediation_replay_results",
    )
    op.drop_index(
        op.f("ix_remediation_replay_results_control_id"), table_name="remediation_replay_results"
    )
    op.drop_index(
        op.f("ix_remediation_replay_results_case_id"), table_name="remediation_replay_results"
    )
    op.drop_table("remediation_replay_results")
    op.drop_index(op.f("ix_proposed_controls_is_active"), table_name="proposed_controls")
    op.drop_table("proposed_controls")
    # ### end Alembic commands ###
