"""
Maps TRIS domain exception error codes to HTTP status codes.
"""

from fastapi import status

HTTP_422 = getattr(status, "HTTP_422_UNPROCESSABLE_CONTENT", 422)

ERROR_STATUS_MAP = {
    "NOT_FOUND": status.HTTP_404_NOT_FOUND,
    "ALREADY_EXISTS": status.HTTP_409_CONFLICT,
    "VALIDATION_ERROR": HTTP_422,
    "VERIFIED_CLOSURE_VALIDATION_ERROR": HTTP_422,
    "INVALID_STATE_TRANSITION": status.HTTP_409_CONFLICT,
    "AUTHENTICATION_FAILED": status.HTTP_401_UNAUTHORIZED,
    "PERMISSION_DENIED": status.HTTP_403_FORBIDDEN,
    "RULE_EXECUTION_ERROR": status.HTTP_400_BAD_REQUEST,
    "INGESTION_ERROR": HTTP_422,
    "DATABASE_INTEGRITY_ERROR": status.HTTP_409_CONFLICT,
}
